# frontend/nginx.conf
server {
    listen 80;
    server_name localhost;

    # 1. A Vue.js frontend kiszolgálása
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. A teljes /api forgalom átirányítása - levágva az /api előtagot
    location /api/ {
        proxy_pass http://excite-backend:8080/; # <-- FIGYELEM: A végén a '/' kötelező!
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
